module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "app-background": "var(--app-background)",
        "black-1": "var(--black-1)",
        "black-2": "var(--black-2)",
        "d-2": "var(--d-2)",
        lime: "var(--lime)",
        "primary-color": "var(--primary-color)",
        white: "var(--white)",
        "x-1st": "var(--x-1st)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        navy: {
          DEFAULT: '#1B2B4A',
          dark: '#15223A',
          light: '#2A3F5F',
        },
        coral: {
          DEFAULT: '#E86C4A',
          dark: '#D85A38',
          light: '#F07E5E',
        },
        cream: {
          DEFAULT: '#F5E6DC',
          dark: '#E8D4C4',
          light: '#FAF2EA',
        },
        burgundy: {
          DEFAULT: '#8B3A3A',
          dark: '#6B2C2C',
          light: '#A04848',
        },
        yellow: {
          accent: '#E8C547',
        },
        primary: {
          DEFAULT: '#181e4b',
        },
        'primary-color': '#181e4b',
        'black-2': '#555770',
        'd-2': '#a54033',
        lime: '#b6e388',
        'app-background': '#f5e6dc',
        card: '#fff8d4',
        border: '#e0e0e0',
        'red-50': '#fef2f2',
        'red-200': '#fecaca',
        'red-500': '#ef4444',
        'white': '#ffffff',
        'gray-300': '#d1d5db',
        'gray-700': '#374151',
        'lime': '#b6e388',
        'f5b75c': '#f5b75c',
        'df6951': '#df6951',
        'c15043': '#c15043',
        '8d3529': '#8d3529',
        '2a3166': '#2a3166',
        'f07e5e': '#F07E5E',
        'e8c547': '#E8C547',
        'a54033': '#a54033',
        'f5e6dc': '#F5E6DC',
        'faf2ea': '#FAF2EA',
        'e8d4c4': '#E8D4C4',
        'df695126': '#df695126',
      fontFamily: {
        sans: [
          'system-ui',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
      },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
